version: "2"
services:
  web-site1:
    image: php-zendserver
    ports: 
     - "9611:80"
    volumes:
     - "./web-site1:/var/www/html"
    networks:
     - frontend

  loadbalancer:
    image: nginx:latest
    networks:
     - frontend 
    #links:
     #- web-site1
     #- web-site2
  web-site2:
    image: php-zendserver
    ports: 
     - "9612:80"
    volumes:
     - "./web-site2:/var/www/html"
    networks:
     - frontend
  pinghost:
    image: debian
    command: ping -d web-site1
    networks:
      - frontend
  db:
    image: mariadb
    #container_name: mysql 
    volumes:
      - ./:/var/lib/mysql  
    ports:
      - "6314:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=netlab
      - MYSQL_DATABASE=bigdata
      - MYSQL_USER_NAME=root
      - MYSQL_PASSWORD=netlab
    networks:
      - frontend
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "9613:80"
    environment:
      - MYSQL_USER_NAME=root
      - MYSQL_ROOT_PASSWORD=netla
      - PMA_HOST=db
    links:
      - db
    networks: 
      - frontend
networks:
    frontend:
            driver: bridge 
